//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rejestr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int IdPeople { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Date_Birth { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    }
}
